/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package view;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import tools.Util;
import view.JDlgFornecedorPesquisar;
import bean.Kea_fornecedor;

public class JDlgFornecedor extends javax.swing.JDialog {

  public JDlgFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro dos Fornecedores");
        
        Util.habilitar(false, jTxtID, jTxtBairro, jTxtCEP, jTxtCNPJ, jTxtCelular, jTxtCidade, jTxtEmail, 
                jTxtInscriMunicip, jTxtLogradouro, jTxtNomeFantasia, jTxtNumero, jTxtRazaoSocial, jTxtUF,
                jRBtnAceitavel, jRBtnAtivo, jRBtnAtraso, jRBtnBoa, jRBtnRuim, jRBtnSuspenso, jRbtnRuim,  jChbBom,  jChbEspecial, jChbExelente,  jChbInsatisfatorio,
                 jChbMonopolista,   jChbRegular, jChbTradicional, jCboCondicacaoPagamento, jBtnCancelar, jBtnConfirmar);
   
    }

    
    public void limpar(){
    jTxtID.setText("");
        jTxtBairro.setText("");
        jTxtCEP.setText("");
        jTxtCNPJ.setText("");
        jTxtCelular.setText("");
        jTxtCidade.setText("");
        jTxtEmail.setText("");
        jTxtInscriMunicip.setText("");
        jTxtLogradouro.setText("");
        jTxtNomeFantasia.setText("");
        jTxtNumero.setText("");
        jTxtRazaoSocial.setText("");
        jTxtUF.setText("");
        jRBtnBoa.setSelected(false);
        jRBtnAceitavel.setSelected(false);
        jRBtnRuim.setSelected(false);
        jRBtnAtivo.setSelected(false);
        jRBtnAtraso.setSelected(false);
        jRBtnSuspenso.setSelected(false);
        jChbBom.setSelected(false);
        jChbEspecial.setSelected(false);
        jChbExelente.setSelected(false);
        jChbInsatisfatorio.setSelected(false);
        jChbMonopolista.setSelected(false);
        jChbRegular.setSelected(false);
        jChbTradicional.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRbtnRuim = new javax.swing.JRadioButton();
        jLblID = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLblRazaoSocial = new javax.swing.JLabel();
        jTxtRazaoSocial = new javax.swing.JTextField();
        jLblEmail = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLblCelular = new javax.swing.JLabel();
        jTxtCelular = new javax.swing.JTextField();
        jLblLogradouro = new javax.swing.JLabel();
        jTxtLogradouro = new javax.swing.JTextField();
        jLblNumero = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        jLblBairro = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        jLblCidade = new javax.swing.JLabel();
        jTxtCidade = new javax.swing.JTextField();
        jLblUF = new javax.swing.JLabel();
        jTxtUF = new javax.swing.JTextField();
        jTxtCEP = new javax.swing.JTextField();
        jLblCEP = new javax.swing.JLabel();
        jLblNomeFantasia = new javax.swing.JLabel();
        jTxtNomeFantasia = new javax.swing.JTextField();
        jLblCNPJ = new javax.swing.JLabel();
        jTxtCNPJ = new javax.swing.JTextField();
        jLblReputacao = new javax.swing.JLabel();
        jRBtnBoa = new javax.swing.JRadioButton();
        jRBtnAceitavel = new javax.swing.JRadioButton();
        jLblSituacao = new javax.swing.JLabel();
        jRBtnAtivo = new javax.swing.JRadioButton();
        jRBtnSuspenso = new javax.swing.JRadioButton();
        jRBtnAtraso = new javax.swing.JRadioButton();
        jRBtnRuim = new javax.swing.JRadioButton();
        jLblInscricaoMunicipal = new javax.swing.JLabel();
        jTxtInscriMunicip = new javax.swing.JTextField();
        jLblCondiPag = new javax.swing.JLabel();
        jLblQualiComp = new javax.swing.JLabel();
        jChbExelente = new javax.swing.JCheckBox();
        jChbBom = new javax.swing.JCheckBox();
        jChbRegular = new javax.swing.JCheckBox();
        jChbInsatisfatorio = new javax.swing.JCheckBox();
        jLblTipoFornecedor = new javax.swing.JLabel();
        jChbTradicional = new javax.swing.JCheckBox();
        jChbMonopolista = new javax.swing.JCheckBox();
        jChbEspecial = new javax.swing.JCheckBox();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jCboCondicacaoPagamento = new javax.swing.JComboBox<>();

        jRbtnRuim.setText("Ruim.");

        jLblID.setText("ID:");

        jTxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIDActionPerformed(evt);
            }
        });

        jLblRazaoSocial.setText("Razao Social:");

        jLblEmail.setText("Email:");

        jLblCelular.setText("Celular:");

        jTxtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCelularActionPerformed(evt);
            }
        });

        jLblLogradouro.setText("Logradouro:");

        jLblNumero.setText("Numero:");

        jLblBairro.setText("Bairro:");

        jLblCidade.setText("Cidade:");

        jLblUF.setText("UF:");

        jLblCEP.setText("CEP:");

        jLblNomeFantasia.setText("Nome Fantasia:");

        jLblCNPJ.setText("CNPJ:");

        jLblReputacao.setText("Reputação:");

        jRBtnBoa.setText("Boa.");
        jRBtnBoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnBoaActionPerformed(evt);
            }
        });

        jRBtnAceitavel.setText("Aceitável.");

        jLblSituacao.setText("Situação:");

        jRBtnAtivo.setText("Ativo.");

        jRBtnSuspenso.setText("Suspenso.");

        jRBtnAtraso.setText("Em atraso.");

        jRBtnRuim.setText("Ruim.");

        jLblInscricaoMunicipal.setText("Inscrição Municipal:");

        jLblCondiPag.setText("Condição de Pagamento:");

        jLblQualiComp.setText("Qualidade de Compra:");

        jChbExelente.setText("Exelente.");

        jChbBom.setText("Bom.");
        jChbBom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbBomActionPerformed(evt);
            }
        });

        jChbRegular.setText("Regular.");

        jChbInsatisfatorio.setText("Insatisfatório.");

        jLblTipoFornecedor.setText("Tipo de Fornecedor:");

        jChbTradicional.setText("Tradicional.");

        jChbMonopolista.setText("Monopolista.");
        jChbMonopolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbMonopolistaActionPerformed(evt);
            }
        });

        jChbEspecial.setText("Especial.");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jCboCondicacaoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartao", "Pix", "Boleto" }));
        jCboCondicacaoPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboCondicacaoPagamentoItemStateChanged(evt);
            }
        });
        jCboCondicacaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCondicacaoPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBtnIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnExcluir)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblReputacao)
                                .addGap(77, 77, 77)
                                .addComponent(jLblSituacao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBtnAceitavel)
                                    .addComponent(jRBtnRuim)
                                    .addComponent(jRBtnBoa))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBtnAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtnSuspenso)
                                    .addComponent(jRBtnAtraso))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChbMonopolista)
                                    .addComponent(jChbTradicional)
                                    .addComponent(jLblTipoFornecedor)
                                    .addComponent(jChbEspecial)
                                    .addComponent(jLblCondiPag)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jBtnConfirmar)
                                        .addGap(137, 137, 137))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jBtnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jBtnPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblBairro)
                                .addGap(330, 330, 330)
                                .addComponent(jLblCEP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblID)
                                .addGap(216, 216, 216)
                                .addComponent(jLblNomeFantasia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLblRazaoSocial)
                                            .addGap(190, 190, 190)
                                            .addComponent(jLblCNPJ))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLblCelular)
                                            .addGap(189, 189, 189)
                                            .addComponent(jLblUF)
                                            .addGap(43, 43, 43)))
                                    .addGap(127, 127, 127))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(jTxtInscriMunicip, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(117, 117, 117)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCidade))
                                .addGap(66, 66, 66)
                                .addComponent(jTxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblLogradouro)
                                .addGap(7, 7, 7)
                                .addComponent(jLblNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblEmail)
                                .addGap(261, 261, 261)
                                .addComponent(jLblInscricaoMunicipal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblQualiComp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jChbBom)
                                            .addComponent(jChbExelente)
                                            .addComponent(jChbRegular)
                                            .addComponent(jChbInsatisfatorio))))))
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jTxtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jTxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jCboCondicacaoPagamento, 0, 0, Short.MAX_VALUE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblID)
                    .addComponent(jLblNomeFantasia))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRazaoSocial)
                    .addComponent(jLblCNPJ)
                    .addComponent(jLblCondiPag))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboCondicacaoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmail)
                    .addComponent(jLblInscricaoMunicipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtInscriMunicip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCelular)
                    .addComponent(jLblUF))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtUF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblLogradouro)
                    .addComponent(jLblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBairro)
                    .addComponent(jLblCEP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblQualiComp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblReputacao)
                    .addComponent(jLblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTipoFornecedor)
                    .addComponent(jChbExelente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnBoa)
                    .addComponent(jRBtnAtivo)
                    .addComponent(jChbTradicional)
                    .addComponent(jChbBom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnAceitavel)
                    .addComponent(jRBtnAtraso)
                    .addComponent(jChbMonopolista)
                    .addComponent(jChbRegular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnRuim)
                    .addComponent(jRBtnSuspenso)
                    .addComponent(jChbEspecial)
                    .addComponent(jChbInsatisfatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBtnBoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnBoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnBoaActionPerformed

    private void jChbBomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbBomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbBomActionPerformed

    private void jChbMonopolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbMonopolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbMonopolistaActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
      Util.habilitar(true, jTxtID, jTxtBairro, jTxtCEP, jTxtCNPJ, jTxtCelular, jTxtCidade, jTxtEmail, 
                jTxtInscriMunicip, jTxtLogradouro, jTxtNomeFantasia, jTxtNumero, jTxtRazaoSocial, jTxtUF,
                jRBtnAceitavel, jRBtnAtivo, jRBtnAtraso, jRBtnBoa, jRBtnRuim, jRBtnSuspenso, jRbtnRuim,  jChbBom,  jChbEspecial, jChbExelente,  jChbInsatisfatorio,
                 jChbMonopolista,   jChbRegular, jChbTradicional, jCboCondicacaoPagamento, jBtnConfirmar, jBtnCancelar);
         Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        limpar();
        jTxtID.grabFocus();
   
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
     
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed

       
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
       
        
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

            
                 
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jTxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIDActionPerformed

    private void jTxtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCelularActionPerformed

    private void jCboCondicacaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCondicacaoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCondicacaoPagamentoActionPerformed

    private void jCboCondicacaoPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboCondicacaoPagamentoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCondicacaoPagamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedor dialog = new JDlgFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboCondicacaoPagamento;
    private javax.swing.JCheckBox jChbBom;
    private javax.swing.JCheckBox jChbEspecial;
    private javax.swing.JCheckBox jChbExelente;
    private javax.swing.JCheckBox jChbInsatisfatorio;
    private javax.swing.JCheckBox jChbMonopolista;
    private javax.swing.JCheckBox jChbRegular;
    private javax.swing.JCheckBox jChbTradicional;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCNPJ;
    private javax.swing.JLabel jLblCelular;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblCondiPag;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblID;
    private javax.swing.JLabel jLblInscricaoMunicipal;
    private javax.swing.JLabel jLblLogradouro;
    private javax.swing.JLabel jLblNomeFantasia;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblQualiComp;
    private javax.swing.JLabel jLblRazaoSocial;
    private javax.swing.JLabel jLblReputacao;
    private javax.swing.JLabel jLblSituacao;
    private javax.swing.JLabel jLblTipoFornecedor;
    private javax.swing.JLabel jLblUF;
    private javax.swing.JRadioButton jRBtnAceitavel;
    private javax.swing.JRadioButton jRBtnAtivo;
    private javax.swing.JRadioButton jRBtnAtraso;
    private javax.swing.JRadioButton jRBtnBoa;
    private javax.swing.JRadioButton jRBtnRuim;
    private javax.swing.JRadioButton jRBtnSuspenso;
    private javax.swing.JRadioButton jRbtnRuim;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCEP;
    private javax.swing.JTextField jTxtCNPJ;
    private javax.swing.JTextField jTxtCelular;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtInscriMunicip;
    private javax.swing.JTextField jTxtLogradouro;
    private javax.swing.JTextField jTxtNomeFantasia;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtRazaoSocial;
    private javax.swing.JTextField jTxtUF;
    // End of variables declaration//GEN-END:variables
}
